name: Token Basics with FabToken Driver

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}
      GOFLAGS: -mod=mod      
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/hyperledger-labs/fabric-token-sdk
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: ${{ env.GOPATH }}/src/github.com/hyperledger-labs/fabric-token-sdk

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Checks
      run: make checks

    - name: Integration Tests
      run: make integration-tests-tcc-fabtoken
